// Comprehensive grocery items database with categories
// Each item has a name and category for auto-sorting in shopping list

export const GROCERY_ITEMS = [
  // Produce - Vegetables
  { name: 'Lettuce', category: 'produce' },
  { name: 'Romaine Lettuce', category: 'produce' },
  { name: 'Spinach', category: 'produce' },
  { name: 'Kale', category: 'produce' },
  { name: 'Arugula', category: 'produce' },
  { name: 'Mixed Greens', category: 'produce' },
  { name: 'Cabbage', category: 'produce' },
  { name: 'Red Cabbage', category: 'produce' },
  { name: 'Tomato', category: 'produce' },
  { name: 'Cherry Tomatoes', category: 'produce' },
  { name: 'Roma Tomatoes', category: 'produce' },
  { name: 'Grape Tomatoes', category: 'produce' },
  { name: 'Onion', category: 'produce' },
  { name: 'Red Onion', category: 'produce' },
  { name: 'Yellow Onion', category: 'produce' },
  { name: 'White Onion', category: 'produce' },
  { name: 'Green Onions', category: 'produce' },
  { name: 'Shallots', category: 'produce' },
  { name: 'Leeks', category: 'produce' },
  { name: 'Garlic', category: 'produce' },
  { name: 'Ginger', category: 'produce' },
  { name: 'Bell Pepper', category: 'produce' },
  { name: 'Red Bell Pepper', category: 'produce' },
  { name: 'Green Bell Pepper', category: 'produce' },
  { name: 'Yellow Bell Pepper', category: 'produce' },
  { name: 'Orange Bell Pepper', category: 'produce' },
  { name: 'Jalapeno', category: 'produce' },
  { name: 'Serrano Pepper', category: 'produce' },
  { name: 'Habanero', category: 'produce' },
  { name: 'Poblano Pepper', category: 'produce' },
  { name: 'Carrot', category: 'produce' },
  { name: 'Baby Carrots', category: 'produce' },
  { name: 'Celery', category: 'produce' },
  { name: 'Cucumber', category: 'produce' },
  { name: 'English Cucumber', category: 'produce' },
  { name: 'Zucchini', category: 'produce' },
  { name: 'Yellow Squash', category: 'produce' },
  { name: 'Butternut Squash', category: 'produce' },
  { name: 'Acorn Squash', category: 'produce' },
  { name: 'Spaghetti Squash', category: 'produce' },
  { name: 'Pumpkin', category: 'produce' },
  { name: 'Broccoli', category: 'produce' },
  { name: 'Broccoli Florets', category: 'produce' },
  { name: 'Cauliflower', category: 'produce' },
  { name: 'Brussels Sprouts', category: 'produce' },
  { name: 'Asparagus', category: 'produce' },
  { name: 'Green Beans', category: 'produce' },
  { name: 'Snap Peas', category: 'produce' },
  { name: 'Snow Peas', category: 'produce' },
  { name: 'Mushrooms', category: 'produce' },
  { name: 'White Mushrooms', category: 'produce' },
  { name: 'Cremini Mushrooms', category: 'produce' },
  { name: 'Portobello Mushrooms', category: 'produce' },
  { name: 'Shiitake Mushrooms', category: 'produce' },
  { name: 'Potato', category: 'produce' },
  { name: 'Russet Potato', category: 'produce' },
  { name: 'Red Potato', category: 'produce' },
  { name: 'Yukon Gold Potato', category: 'produce' },
  { name: 'Sweet Potato', category: 'produce' },
  { name: 'Yam', category: 'produce' },
  { name: 'Corn', category: 'produce' },
  { name: 'Corn on the Cob', category: 'produce' },
  { name: 'Eggplant', category: 'produce' },
  { name: 'Artichoke', category: 'produce' },
  { name: 'Avocado', category: 'produce' },
  { name: 'Beet', category: 'produce' },
  { name: 'Radish', category: 'produce' },
  { name: 'Turnip', category: 'produce' },
  { name: 'Parsnip', category: 'produce' },
  { name: 'Fennel', category: 'produce' },
  { name: 'Bok Choy', category: 'produce' },
  { name: 'Swiss Chard', category: 'produce' },
  { name: 'Collard Greens', category: 'produce' },

  // Produce - Fruits
  { name: 'Apple', category: 'produce' },
  { name: 'Granny Smith Apple', category: 'produce' },
  { name: 'Fuji Apple', category: 'produce' },
  { name: 'Gala Apple', category: 'produce' },
  { name: 'Honeycrisp Apple', category: 'produce' },
  { name: 'Banana', category: 'produce' },
  { name: 'Orange', category: 'produce' },
  { name: 'Navel Orange', category: 'produce' },
  { name: 'Blood Orange', category: 'produce' },
  { name: 'Mandarin Orange', category: 'produce' },
  { name: 'Clementine', category: 'produce' },
  { name: 'Tangerine', category: 'produce' },
  { name: 'Lemon', category: 'produce' },
  { name: 'Lime', category: 'produce' },
  { name: 'Grapefruit', category: 'produce' },
  { name: 'Strawberries', category: 'produce' },
  { name: 'Blueberries', category: 'produce' },
  { name: 'Raspberries', category: 'produce' },
  { name: 'Blackberries', category: 'produce' },
  { name: 'Cranberries', category: 'produce' },
  { name: 'Grapes', category: 'produce' },
  { name: 'Red Grapes', category: 'produce' },
  { name: 'Green Grapes', category: 'produce' },
  { name: 'Watermelon', category: 'produce' },
  { name: 'Cantaloupe', category: 'produce' },
  { name: 'Honeydew', category: 'produce' },
  { name: 'Pineapple', category: 'produce' },
  { name: 'Mango', category: 'produce' },
  { name: 'Papaya', category: 'produce' },
  { name: 'Kiwi', category: 'produce' },
  { name: 'Peach', category: 'produce' },
  { name: 'Nectarine', category: 'produce' },
  { name: 'Plum', category: 'produce' },
  { name: 'Apricot', category: 'produce' },
  { name: 'Cherry', category: 'produce' },
  { name: 'Pear', category: 'produce' },
  { name: 'Pomegranate', category: 'produce' },
  { name: 'Fig', category: 'produce' },
  { name: 'Dates', category: 'produce' },
  { name: 'Coconut', category: 'produce' },
  { name: 'Persimmon', category: 'produce' },
  { name: 'Dragon Fruit', category: 'produce' },
  { name: 'Passion Fruit', category: 'produce' },
  { name: 'Guava', category: 'produce' },
  { name: 'Lychee', category: 'produce' },

  // Produce - Herbs
  { name: 'Basil', category: 'produce' },
  { name: 'Cilantro', category: 'produce' },
  { name: 'Parsley', category: 'produce' },
  { name: 'Flat Leaf Parsley', category: 'produce' },
  { name: 'Mint', category: 'produce' },
  { name: 'Dill', category: 'produce' },
  { name: 'Rosemary', category: 'produce' },
  { name: 'Thyme', category: 'produce' },
  { name: 'Sage', category: 'produce' },
  { name: 'Oregano (Fresh)', category: 'produce' },
  { name: 'Chives', category: 'produce' },
  { name: 'Tarragon', category: 'produce' },
  { name: 'Bay Leaves (Fresh)', category: 'produce' },
  { name: 'Lemongrass', category: 'produce' },

  // Dairy & Eggs
  { name: 'Milk', category: 'dairy' },
  { name: 'Whole Milk', category: 'dairy' },
  { name: '2% Milk', category: 'dairy' },
  { name: 'Skim Milk', category: 'dairy' },
  { name: 'Almond Milk', category: 'dairy' },
  { name: 'Oat Milk', category: 'dairy' },
  { name: 'Soy Milk', category: 'dairy' },
  { name: 'Coconut Milk', category: 'dairy' },
  { name: 'Half and Half', category: 'dairy' },
  { name: 'Heavy Cream', category: 'dairy' },
  { name: 'Whipping Cream', category: 'dairy' },
  { name: 'Sour Cream', category: 'dairy' },
  { name: 'Buttermilk', category: 'dairy' },
  { name: 'Evaporated Milk', category: 'dairy' },
  { name: 'Condensed Milk', category: 'dairy' },
  { name: 'Butter', category: 'dairy' },
  { name: 'Unsalted Butter', category: 'dairy' },
  { name: 'Salted Butter', category: 'dairy' },
  { name: 'Margarine', category: 'dairy' },
  { name: 'Ghee', category: 'dairy' },
  { name: 'Eggs', category: 'dairy' },
  { name: 'Large Eggs', category: 'dairy' },
  { name: 'Egg Whites', category: 'dairy' },
  { name: 'Cheese', category: 'dairy' },
  { name: 'Cheddar Cheese', category: 'dairy' },
  { name: 'Sharp Cheddar', category: 'dairy' },
  { name: 'Mild Cheddar', category: 'dairy' },
  { name: 'Mozzarella', category: 'dairy' },
  { name: 'Fresh Mozzarella', category: 'dairy' },
  { name: 'Shredded Mozzarella', category: 'dairy' },
  { name: 'Parmesan', category: 'dairy' },
  { name: 'Pecorino Romano', category: 'dairy' },
  { name: 'Swiss Cheese', category: 'dairy' },
  { name: 'Provolone', category: 'dairy' },
  { name: 'Gouda', category: 'dairy' },
  { name: 'Brie', category: 'dairy' },
  { name: 'Feta Cheese', category: 'dairy' },
  { name: 'Goat Cheese', category: 'dairy' },
  { name: 'Blue Cheese', category: 'dairy' },
  { name: 'Gorgonzola', category: 'dairy' },
  { name: 'Cream Cheese', category: 'dairy' },
  { name: 'Ricotta', category: 'dairy' },
  { name: 'Cottage Cheese', category: 'dairy' },
  { name: 'Mascarpone', category: 'dairy' },
  { name: 'American Cheese', category: 'dairy' },
  { name: 'Monterey Jack', category: 'dairy' },
  { name: 'Pepper Jack', category: 'dairy' },
  { name: 'Colby Jack', category: 'dairy' },
  { name: 'Gruyere', category: 'dairy' },
  { name: 'Havarti', category: 'dairy' },
  { name: 'Yogurt', category: 'dairy' },
  { name: 'Greek Yogurt', category: 'dairy' },
  { name: 'Plain Yogurt', category: 'dairy' },
  { name: 'Vanilla Yogurt', category: 'dairy' },
  { name: 'Kefir', category: 'dairy' },

  // Meat & Seafood
  { name: 'Chicken Breast', category: 'meat' },
  { name: 'Chicken Thighs', category: 'meat' },
  { name: 'Chicken Drumsticks', category: 'meat' },
  { name: 'Chicken Wings', category: 'meat' },
  { name: 'Whole Chicken', category: 'meat' },
  { name: 'Ground Chicken', category: 'meat' },
  { name: 'Rotisserie Chicken', category: 'meat' },
  { name: 'Turkey Breast', category: 'meat' },
  { name: 'Ground Turkey', category: 'meat' },
  { name: 'Turkey Bacon', category: 'meat' },
  { name: 'Ground Beef', category: 'meat' },
  { name: 'Lean Ground Beef', category: 'meat' },
  { name: 'Beef Steak', category: 'meat' },
  { name: 'Ribeye Steak', category: 'meat' },
  { name: 'Sirloin Steak', category: 'meat' },
  { name: 'NY Strip Steak', category: 'meat' },
  { name: 'Filet Mignon', category: 'meat' },
  { name: 'Flank Steak', category: 'meat' },
  { name: 'Skirt Steak', category: 'meat' },
  { name: 'Beef Roast', category: 'meat' },
  { name: 'Chuck Roast', category: 'meat' },
  { name: 'Brisket', category: 'meat' },
  { name: 'Beef Short Ribs', category: 'meat' },
  { name: 'Stew Meat', category: 'meat' },
  { name: 'Pork Chops', category: 'meat' },
  { name: 'Pork Tenderloin', category: 'meat' },
  { name: 'Pork Loin', category: 'meat' },
  { name: 'Pork Shoulder', category: 'meat' },
  { name: 'Ground Pork', category: 'meat' },
  { name: 'Pork Ribs', category: 'meat' },
  { name: 'Baby Back Ribs', category: 'meat' },
  { name: 'Bacon', category: 'meat' },
  { name: 'Thick Cut Bacon', category: 'meat' },
  { name: 'Canadian Bacon', category: 'meat' },
  { name: 'Pancetta', category: 'meat' },
  { name: 'Ham', category: 'meat' },
  { name: 'Deli Ham', category: 'meat' },
  { name: 'Prosciutto', category: 'meat' },
  { name: 'Sausage', category: 'meat' },
  { name: 'Italian Sausage', category: 'meat' },
  { name: 'Breakfast Sausage', category: 'meat' },
  { name: 'Chorizo', category: 'meat' },
  { name: 'Bratwurst', category: 'meat' },
  { name: 'Kielbasa', category: 'meat' },
  { name: 'Andouille Sausage', category: 'meat' },
  { name: 'Hot Dogs', category: 'meat' },
  { name: 'Pepperoni', category: 'meat' },
  { name: 'Salami', category: 'meat' },
  { name: 'Lamb Chops', category: 'meat' },
  { name: 'Ground Lamb', category: 'meat' },
  { name: 'Lamb Leg', category: 'meat' },
  { name: 'Veal', category: 'meat' },
  { name: 'Duck', category: 'meat' },
  { name: 'Duck Breast', category: 'meat' },
  { name: 'Salmon', category: 'meat' },
  { name: 'Salmon Fillet', category: 'meat' },
  { name: 'Smoked Salmon', category: 'meat' },
  { name: 'Tuna', category: 'meat' },
  { name: 'Tuna Steak', category: 'meat' },
  { name: 'Canned Tuna', category: 'pantry' },
  { name: 'Tilapia', category: 'meat' },
  { name: 'Cod', category: 'meat' },
  { name: 'Halibut', category: 'meat' },
  { name: 'Mahi Mahi', category: 'meat' },
  { name: 'Sea Bass', category: 'meat' },
  { name: 'Snapper', category: 'meat' },
  { name: 'Trout', category: 'meat' },
  { name: 'Catfish', category: 'meat' },
  { name: 'Swordfish', category: 'meat' },
  { name: 'Sardines', category: 'meat' },
  { name: 'Anchovies', category: 'meat' },
  { name: 'Shrimp', category: 'meat' },
  { name: 'Large Shrimp', category: 'meat' },
  { name: 'Jumbo Shrimp', category: 'meat' },
  { name: 'Cocktail Shrimp', category: 'meat' },
  { name: 'Crab', category: 'meat' },
  { name: 'Crab Meat', category: 'meat' },
  { name: 'Crab Legs', category: 'meat' },
  { name: 'Lobster', category: 'meat' },
  { name: 'Lobster Tail', category: 'meat' },
  { name: 'Scallops', category: 'meat' },
  { name: 'Mussels', category: 'meat' },
  { name: 'Clams', category: 'meat' },
  { name: 'Oysters', category: 'meat' },
  { name: 'Calamari', category: 'meat' },
  { name: 'Octopus', category: 'meat' },

  // Bakery & Bread
  { name: 'White Bread', category: 'bakery' },
  { name: 'Whole Wheat Bread', category: 'bakery' },
  { name: 'Sourdough Bread', category: 'bakery' },
  { name: 'French Bread', category: 'bakery' },
  { name: 'Italian Bread', category: 'bakery' },
  { name: 'Ciabatta', category: 'bakery' },
  { name: 'Baguette', category: 'bakery' },
  { name: 'Rye Bread', category: 'bakery' },
  { name: 'Pumpernickel', category: 'bakery' },
  { name: 'Brioche', category: 'bakery' },
  { name: 'Focaccia', category: 'bakery' },
  { name: 'Naan', category: 'bakery' },
  { name: 'Pita Bread', category: 'bakery' },
  { name: 'Tortillas', category: 'bakery' },
  { name: 'Flour Tortillas', category: 'bakery' },
  { name: 'Corn Tortillas', category: 'bakery' },
  { name: 'Hamburger Buns', category: 'bakery' },
  { name: 'Hot Dog Buns', category: 'bakery' },
  { name: 'Hoagie Rolls', category: 'bakery' },
  { name: 'Dinner Rolls', category: 'bakery' },
  { name: 'Kaiser Rolls', category: 'bakery' },
  { name: 'Bagels', category: 'bakery' },
  { name: 'Plain Bagels', category: 'bakery' },
  { name: 'Everything Bagels', category: 'bakery' },
  { name: 'English Muffins', category: 'bakery' },
  { name: 'Croissants', category: 'bakery' },
  { name: 'Muffins', category: 'bakery' },
  { name: 'Donuts', category: 'bakery' },
  { name: 'Breadcrumbs', category: 'bakery' },
  { name: 'Panko', category: 'bakery' },
  { name: 'Croutons', category: 'bakery' },
  { name: 'Cornbread', category: 'bakery' },
  { name: 'Flatbread', category: 'bakery' },
  { name: 'Lavash', category: 'bakery' },
  { name: 'Pretzel', category: 'bakery' },

  // Pantry - Grains & Pasta
  { name: 'All-Purpose Flour', category: 'pantry' },
  { name: 'Bread Flour', category: 'pantry' },
  { name: 'Whole Wheat Flour', category: 'pantry' },
  { name: 'Cake Flour', category: 'pantry' },
  { name: 'Almond Flour', category: 'pantry' },
  { name: 'Coconut Flour', category: 'pantry' },
  { name: 'Cornmeal', category: 'pantry' },
  { name: 'Cornstarch', category: 'pantry' },
  { name: 'White Rice', category: 'pantry' },
  { name: 'Brown Rice', category: 'pantry' },
  { name: 'Jasmine Rice', category: 'pantry' },
  { name: 'Basmati Rice', category: 'pantry' },
  { name: 'Arborio Rice', category: 'pantry' },
  { name: 'Wild Rice', category: 'pantry' },
  { name: 'Quinoa', category: 'pantry' },
  { name: 'Couscous', category: 'pantry' },
  { name: 'Bulgur', category: 'pantry' },
  { name: 'Farro', category: 'pantry' },
  { name: 'Barley', category: 'pantry' },
  { name: 'Oats', category: 'pantry' },
  { name: 'Rolled Oats', category: 'pantry' },
  { name: 'Steel Cut Oats', category: 'pantry' },
  { name: 'Instant Oatmeal', category: 'pantry' },
  { name: 'Polenta', category: 'pantry' },
  { name: 'Grits', category: 'pantry' },
  { name: 'Spaghetti', category: 'pantry' },
  { name: 'Penne', category: 'pantry' },
  { name: 'Rigatoni', category: 'pantry' },
  { name: 'Fettuccine', category: 'pantry' },
  { name: 'Linguine', category: 'pantry' },
  { name: 'Angel Hair', category: 'pantry' },
  { name: 'Macaroni', category: 'pantry' },
  { name: 'Elbow Macaroni', category: 'pantry' },
  { name: 'Rotini', category: 'pantry' },
  { name: 'Farfalle', category: 'pantry' },
  { name: 'Orzo', category: 'pantry' },
  { name: 'Lasagna Noodles', category: 'pantry' },
  { name: 'Egg Noodles', category: 'pantry' },
  { name: 'Rice Noodles', category: 'pantry' },
  { name: 'Ramen Noodles', category: 'pantry' },
  { name: 'Udon Noodles', category: 'pantry' },
  { name: 'Soba Noodles', category: 'pantry' },
  { name: 'Gnocchi', category: 'pantry' },

  // Pantry - Canned & Jarred
  { name: 'Diced Tomatoes', category: 'pantry' },
  { name: 'Crushed Tomatoes', category: 'pantry' },
  { name: 'Tomato Sauce', category: 'pantry' },
  { name: 'Tomato Paste', category: 'pantry' },
  { name: 'Sun-Dried Tomatoes', category: 'pantry' },
  { name: 'Marinara Sauce', category: 'pantry' },
  { name: 'Pizza Sauce', category: 'pantry' },
  { name: 'Alfredo Sauce', category: 'pantry' },
  { name: 'Pesto', category: 'pantry' },
  { name: 'Salsa', category: 'pantry' },
  { name: 'Black Beans', category: 'pantry' },
  { name: 'Kidney Beans', category: 'pantry' },
  { name: 'Pinto Beans', category: 'pantry' },
  { name: 'Cannellini Beans', category: 'pantry' },
  { name: 'Navy Beans', category: 'pantry' },
  { name: 'Chickpeas', category: 'pantry' },
  { name: 'Lentils', category: 'pantry' },
  { name: 'Red Lentils', category: 'pantry' },
  { name: 'Green Lentils', category: 'pantry' },
  { name: 'Refried Beans', category: 'pantry' },
  { name: 'Baked Beans', category: 'pantry' },
  { name: 'Corn (Canned)', category: 'pantry' },
  { name: 'Green Beans (Canned)', category: 'pantry' },
  { name: 'Peas (Canned)', category: 'pantry' },
  { name: 'Mushrooms (Canned)', category: 'pantry' },
  { name: 'Olives', category: 'pantry' },
  { name: 'Black Olives', category: 'pantry' },
  { name: 'Kalamata Olives', category: 'pantry' },
  { name: 'Green Olives', category: 'pantry' },
  { name: 'Capers', category: 'pantry' },
  { name: 'Artichoke Hearts', category: 'pantry' },
  { name: 'Roasted Red Peppers', category: 'pantry' },
  { name: 'Pickles', category: 'pantry' },
  { name: 'Dill Pickles', category: 'pantry' },
  { name: 'Sauerkraut', category: 'pantry' },
  { name: 'Chicken Broth', category: 'pantry' },
  { name: 'Beef Broth', category: 'pantry' },
  { name: 'Vegetable Broth', category: 'pantry' },
  { name: 'Chicken Stock', category: 'pantry' },
  { name: 'Beef Stock', category: 'pantry' },
  { name: 'Coconut Milk (Canned)', category: 'pantry' },

  // Pantry - Oils & Vinegars
  { name: 'Olive Oil', category: 'pantry' },
  { name: 'Extra Virgin Olive Oil', category: 'pantry' },
  { name: 'Vegetable Oil', category: 'pantry' },
  { name: 'Canola Oil', category: 'pantry' },
  { name: 'Coconut Oil', category: 'pantry' },
  { name: 'Avocado Oil', category: 'pantry' },
  { name: 'Sesame Oil', category: 'pantry' },
  { name: 'Peanut Oil', category: 'pantry' },
  { name: 'Grapeseed Oil', category: 'pantry' },
  { name: 'Cooking Spray', category: 'pantry' },
  { name: 'White Vinegar', category: 'pantry' },
  { name: 'Apple Cider Vinegar', category: 'pantry' },
  { name: 'Red Wine Vinegar', category: 'pantry' },
  { name: 'White Wine Vinegar', category: 'pantry' },
  { name: 'Balsamic Vinegar', category: 'pantry' },
  { name: 'Rice Vinegar', category: 'pantry' },
  { name: 'Sherry Vinegar', category: 'pantry' },

  // Pantry - Sweeteners & Baking
  { name: 'White Sugar', category: 'pantry' },
  { name: 'Brown Sugar', category: 'pantry' },
  { name: 'Powdered Sugar', category: 'pantry' },
  { name: 'Honey', category: 'pantry' },
  { name: 'Maple Syrup', category: 'pantry' },
  { name: 'Agave Nectar', category: 'pantry' },
  { name: 'Molasses', category: 'pantry' },
  { name: 'Corn Syrup', category: 'pantry' },
  { name: 'Stevia', category: 'pantry' },
  { name: 'Baking Powder', category: 'pantry' },
  { name: 'Baking Soda', category: 'pantry' },
  { name: 'Yeast', category: 'pantry' },
  { name: 'Active Dry Yeast', category: 'pantry' },
  { name: 'Instant Yeast', category: 'pantry' },
  { name: 'Vanilla Extract', category: 'pantry' },
  { name: 'Almond Extract', category: 'pantry' },
  { name: 'Cocoa Powder', category: 'pantry' },
  { name: 'Chocolate Chips', category: 'pantry' },
  { name: 'Dark Chocolate', category: 'pantry' },
  { name: 'Milk Chocolate', category: 'pantry' },
  { name: 'White Chocolate', category: 'pantry' },
  { name: 'Baking Chocolate', category: 'pantry' },
  { name: 'Gelatin', category: 'pantry' },

  // Pantry - Condiments & Sauces
  { name: 'Ketchup', category: 'pantry' },
  { name: 'Mustard', category: 'pantry' },
  { name: 'Yellow Mustard', category: 'pantry' },
  { name: 'Dijon Mustard', category: 'pantry' },
  { name: 'Whole Grain Mustard', category: 'pantry' },
  { name: 'Mayonnaise', category: 'pantry' },
  { name: 'Ranch Dressing', category: 'pantry' },
  { name: 'Italian Dressing', category: 'pantry' },
  { name: 'Caesar Dressing', category: 'pantry' },
  { name: 'Blue Cheese Dressing', category: 'pantry' },
  { name: 'Thousand Island Dressing', category: 'pantry' },
  { name: 'Vinaigrette', category: 'pantry' },
  { name: 'Soy Sauce', category: 'pantry' },
  { name: 'Low Sodium Soy Sauce', category: 'pantry' },
  { name: 'Tamari', category: 'pantry' },
  { name: 'Fish Sauce', category: 'pantry' },
  { name: 'Oyster Sauce', category: 'pantry' },
  { name: 'Hoisin Sauce', category: 'pantry' },
  { name: 'Teriyaki Sauce', category: 'pantry' },
  { name: 'Sriracha', category: 'pantry' },
  { name: 'Hot Sauce', category: 'pantry' },
  { name: 'Tabasco', category: 'pantry' },
  { name: 'BBQ Sauce', category: 'pantry' },
  { name: 'Worcestershire Sauce', category: 'pantry' },
  { name: 'Steak Sauce', category: 'pantry' },
  { name: 'Relish', category: 'pantry' },
  { name: 'Horseradish', category: 'pantry' },
  { name: 'Tahini', category: 'pantry' },
  { name: 'Hummus', category: 'pantry' },
  { name: 'Peanut Butter', category: 'pantry' },
  { name: 'Almond Butter', category: 'pantry' },
  { name: 'Nutella', category: 'pantry' },
  { name: 'Jam', category: 'pantry' },
  { name: 'Strawberry Jam', category: 'pantry' },
  { name: 'Grape Jelly', category: 'pantry' },
  { name: 'Marmalade', category: 'pantry' },

  // Pantry - Nuts & Dried Fruits
  { name: 'Almonds', category: 'pantry' },
  { name: 'Sliced Almonds', category: 'pantry' },
  { name: 'Walnuts', category: 'pantry' },
  { name: 'Pecans', category: 'pantry' },
  { name: 'Cashews', category: 'pantry' },
  { name: 'Peanuts', category: 'pantry' },
  { name: 'Pistachios', category: 'pantry' },
  { name: 'Macadamia Nuts', category: 'pantry' },
  { name: 'Pine Nuts', category: 'pantry' },
  { name: 'Hazelnuts', category: 'pantry' },
  { name: 'Mixed Nuts', category: 'pantry' },
  { name: 'Sunflower Seeds', category: 'pantry' },
  { name: 'Pumpkin Seeds', category: 'pantry' },
  { name: 'Sesame Seeds', category: 'pantry' },
  { name: 'Chia Seeds', category: 'pantry' },
  { name: 'Flax Seeds', category: 'pantry' },
  { name: 'Hemp Seeds', category: 'pantry' },
  { name: 'Raisins', category: 'pantry' },
  { name: 'Dried Cranberries', category: 'pantry' },
  { name: 'Dried Apricots', category: 'pantry' },
  { name: 'Dried Cherries', category: 'pantry' },
  { name: 'Dried Mango', category: 'pantry' },
  { name: 'Dried Figs', category: 'pantry' },
  { name: 'Prunes', category: 'pantry' },
  { name: 'Coconut Flakes', category: 'pantry' },
  { name: 'Shredded Coconut', category: 'pantry' },

  // Spices & Seasonings
  { name: 'Salt', category: 'spices' },
  { name: 'Sea Salt', category: 'spices' },
  { name: 'Kosher Salt', category: 'spices' },
  { name: 'Black Pepper', category: 'spices' },
  { name: 'White Pepper', category: 'spices' },
  { name: 'Peppercorns', category: 'spices' },
  { name: 'Red Pepper Flakes', category: 'spices' },
  { name: 'Cayenne Pepper', category: 'spices' },
  { name: 'Paprika', category: 'spices' },
  { name: 'Smoked Paprika', category: 'spices' },
  { name: 'Hungarian Paprika', category: 'spices' },
  { name: 'Chili Powder', category: 'spices' },
  { name: 'Chipotle Powder', category: 'spices' },
  { name: 'Cumin', category: 'spices' },
  { name: 'Ground Cumin', category: 'spices' },
  { name: 'Cumin Seeds', category: 'spices' },
  { name: 'Coriander', category: 'spices' },
  { name: 'Ground Coriander', category: 'spices' },
  { name: 'Turmeric', category: 'spices' },
  { name: 'Curry Powder', category: 'spices' },
  { name: 'Garam Masala', category: 'spices' },
  { name: 'Cinnamon', category: 'spices' },
  { name: 'Ground Cinnamon', category: 'spices' },
  { name: 'Cinnamon Sticks', category: 'spices' },
  { name: 'Nutmeg', category: 'spices' },
  { name: 'Allspice', category: 'spices' },
  { name: 'Cloves', category: 'spices' },
  { name: 'Ground Cloves', category: 'spices' },
  { name: 'Cardamom', category: 'spices' },
  { name: 'Star Anise', category: 'spices' },
  { name: 'Fennel Seeds', category: 'spices' },
  { name: 'Mustard Seeds', category: 'spices' },
  { name: 'Celery Seed', category: 'spices' },
  { name: 'Caraway Seeds', category: 'spices' },
  { name: 'Oregano', category: 'spices' },
  { name: 'Dried Oregano', category: 'spices' },
  { name: 'Basil (Dried)', category: 'spices' },
  { name: 'Thyme (Dried)', category: 'spices' },
  { name: 'Rosemary (Dried)', category: 'spices' },
  { name: 'Sage (Dried)', category: 'spices' },
  { name: 'Parsley (Dried)', category: 'spices' },
  { name: 'Dill (Dried)', category: 'spices' },
  { name: 'Bay Leaves', category: 'spices' },
  { name: 'Italian Seasoning', category: 'spices' },
  { name: 'Herbs de Provence', category: 'spices' },
  { name: 'Poultry Seasoning', category: 'spices' },
  { name: 'Old Bay Seasoning', category: 'spices' },
  { name: 'Cajun Seasoning', category: 'spices' },
  { name: 'Taco Seasoning', category: 'spices' },
  { name: 'Ranch Seasoning', category: 'spices' },
  { name: 'Everything Bagel Seasoning', category: 'spices' },
  { name: 'Garlic Powder', category: 'spices' },
  { name: 'Onion Powder', category: 'spices' },
  { name: 'Garlic Salt', category: 'spices' },
  { name: 'Onion Salt', category: 'spices' },
  { name: 'Seasoned Salt', category: 'spices' },
  { name: 'Lemon Pepper', category: 'spices' },
  { name: 'MSG', category: 'spices' },
  { name: 'Bouillon Cubes', category: 'spices' },
  { name: 'Chicken Bouillon', category: 'spices' },
  { name: 'Beef Bouillon', category: 'spices' },
  { name: 'Saffron', category: 'spices' },
  { name: 'Vanilla Bean', category: 'spices' },

  // Frozen
  { name: 'Frozen Vegetables', category: 'frozen' },
  { name: 'Frozen Peas', category: 'frozen' },
  { name: 'Frozen Corn', category: 'frozen' },
  { name: 'Frozen Broccoli', category: 'frozen' },
  { name: 'Frozen Spinach', category: 'frozen' },
  { name: 'Frozen Green Beans', category: 'frozen' },
  { name: 'Frozen Mixed Vegetables', category: 'frozen' },
  { name: 'Frozen Stir Fry Vegetables', category: 'frozen' },
  { name: 'Frozen Berries', category: 'frozen' },
  { name: 'Frozen Strawberries', category: 'frozen' },
  { name: 'Frozen Blueberries', category: 'frozen' },
  { name: 'Frozen Raspberries', category: 'frozen' },
  { name: 'Frozen Mixed Fruit', category: 'frozen' },
  { name: 'Frozen Mango', category: 'frozen' },
  { name: 'Frozen Peaches', category: 'frozen' },
  { name: 'Frozen Pizza', category: 'frozen' },
  { name: 'Frozen French Fries', category: 'frozen' },
  { name: 'Frozen Tater Tots', category: 'frozen' },
  { name: 'Frozen Hash Browns', category: 'frozen' },
  { name: 'Frozen Waffles', category: 'frozen' },
  { name: 'Frozen Pancakes', category: 'frozen' },
  { name: 'Frozen Burritos', category: 'frozen' },
  { name: 'Frozen Chicken Nuggets', category: 'frozen' },
  { name: 'Frozen Fish Sticks', category: 'frozen' },
  { name: 'Frozen Shrimp', category: 'frozen' },
  { name: 'Ice Cream', category: 'frozen' },
  { name: 'Vanilla Ice Cream', category: 'frozen' },
  { name: 'Chocolate Ice Cream', category: 'frozen' },
  { name: 'Frozen Yogurt', category: 'frozen' },
  { name: 'Sorbet', category: 'frozen' },
  { name: 'Gelato', category: 'frozen' },
  { name: 'Ice Pops', category: 'frozen' },
  { name: 'Pie Crust', category: 'frozen' },
  { name: 'Puff Pastry', category: 'frozen' },
  { name: 'Phyllo Dough', category: 'frozen' },

  // Beverages
  { name: 'Water', category: 'beverages' },
  { name: 'Sparkling Water', category: 'beverages' },
  { name: 'Seltzer', category: 'beverages' },
  { name: 'Club Soda', category: 'beverages' },
  { name: 'Tonic Water', category: 'beverages' },
  { name: 'Orange Juice', category: 'beverages' },
  { name: 'Apple Juice', category: 'beverages' },
  { name: 'Grape Juice', category: 'beverages' },
  { name: 'Cranberry Juice', category: 'beverages' },
  { name: 'Pineapple Juice', category: 'beverages' },
  { name: 'Tomato Juice', category: 'beverages' },
  { name: 'Lemonade', category: 'beverages' },
  { name: 'Limeade', category: 'beverages' },
  { name: 'Iced Tea', category: 'beverages' },
  { name: 'Sweet Tea', category: 'beverages' },
  { name: 'Coca-Cola', category: 'beverages' },
  { name: 'Pepsi', category: 'beverages' },
  { name: 'Sprite', category: 'beverages' },
  { name: 'Ginger Ale', category: 'beverages' },
  { name: 'Root Beer', category: 'beverages' },
  { name: 'Dr Pepper', category: 'beverages' },
  { name: 'Mountain Dew', category: 'beverages' },
  { name: 'Energy Drink', category: 'beverages' },
  { name: 'Coffee', category: 'beverages' },
  { name: 'Ground Coffee', category: 'beverages' },
  { name: 'Coffee Beans', category: 'beverages' },
  { name: 'Instant Coffee', category: 'beverages' },
  { name: 'Espresso', category: 'beverages' },
  { name: 'Cold Brew', category: 'beverages' },
  { name: 'Tea', category: 'beverages' },
  { name: 'Black Tea', category: 'beverages' },
  { name: 'Green Tea', category: 'beverages' },
  { name: 'Herbal Tea', category: 'beverages' },
  { name: 'Chamomile Tea', category: 'beverages' },
  { name: 'Peppermint Tea', category: 'beverages' },
  { name: 'Earl Grey', category: 'beverages' },
  { name: 'Chai Tea', category: 'beverages' },
  { name: 'Matcha', category: 'beverages' },
  { name: 'Hot Chocolate', category: 'beverages' },
  { name: 'Wine', category: 'beverages' },
  { name: 'Red Wine', category: 'beverages' },
  { name: 'White Wine', category: 'beverages' },
  { name: 'Rose Wine', category: 'beverages' },
  { name: 'Champagne', category: 'beverages' },
  { name: 'Prosecco', category: 'beverages' },
  { name: 'Beer', category: 'beverages' },
  { name: 'Lager', category: 'beverages' },
  { name: 'IPA', category: 'beverages' },
  { name: 'Stout', category: 'beverages' },
  { name: 'Hard Cider', category: 'beverages' },
  { name: 'Vodka', category: 'beverages' },
  { name: 'Rum', category: 'beverages' },
  { name: 'Whiskey', category: 'beverages' },
  { name: 'Bourbon', category: 'beverages' },
  { name: 'Scotch', category: 'beverages' },
  { name: 'Gin', category: 'beverages' },
  { name: 'Tequila', category: 'beverages' },
  { name: 'Brandy', category: 'beverages' },
  { name: 'Cognac', category: 'beverages' },
  { name: 'Vermouth', category: 'beverages' },
  { name: 'Triple Sec', category: 'beverages' },
  { name: 'Kahlua', category: 'beverages' },
  { name: 'Baileys', category: 'beverages' },
  { name: 'Sake', category: 'beverages' },
  { name: 'Mirin', category: 'beverages' },
  { name: 'Cooking Wine', category: 'beverages' },
  { name: 'Sherry', category: 'beverages' },
  { name: 'Marsala Wine', category: 'beverages' }
]

// Search grocery items by name
export function searchGroceryItems(query, limit = 10) {
  if (!query || query.trim().length < 2) return []

  const lowerQuery = query.toLowerCase().trim()

  // Score items based on match quality
  const scored = GROCERY_ITEMS.map(item => {
    const lowerName = item.name.toLowerCase()
    let score = 0

    // Exact match
    if (lowerName === lowerQuery) {
      score = 100
    }
    // Starts with query
    else if (lowerName.startsWith(lowerQuery)) {
      score = 80
    }
    // Word starts with query
    else if (lowerName.split(' ').some(word => word.startsWith(lowerQuery))) {
      score = 60
    }
    // Contains query
    else if (lowerName.includes(lowerQuery)) {
      score = 40
    }

    return { ...item, score }
  })

  // Filter and sort by score, then alphabetically
  return scored
    .filter(item => item.score > 0)
    .sort((a, b) => b.score - a.score || a.name.localeCompare(b.name))
    .slice(0, limit)
    .map(({ score, ...item }) => item)
}

// Get all unique categories
export function getGroceryCategories() {
  const categories = new Set(GROCERY_ITEMS.map(item => item.category))
  return [...categories]
}
